- name: apt install programs
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ programs_apt }}"

- name: snap install programs
  become: yes
  command: snap install "{{ item }}" --classic
  loop: "{{ programs_snap }}"
